// Generated by npm run build:textures. Only existing assets are redirected.
export const TEXTURE_VARIANTS: Record<string, { low: string; med: string }> = {
  "/shared-models/angel-statue/scene-low.glb": {
    "low": "/graphics/low/shared-models/angel-statue/scene-low.glb",
    "med": "/graphics/med/shared-models/angel-statue/scene-low.glb"
  },
  "/shared-models/angel-statue/textures/lowpolyangel99_u1_v1_baseColor.png": {
    "low": "/graphics/low/shared-models/angel-statue/textures/lowpolyangel99_u1_v1_baseColor.png",
    "med": "/graphics/med/shared-models/angel-statue/textures/lowpolyangel99_u1_v1_baseColor.png"
  },
  "/shared-models/angel-statue/textures/lowpolyangel99_u1_v1_normal.png": {
    "low": "/graphics/low/shared-models/angel-statue/textures/lowpolyangel99_u1_v1_normal.png",
    "med": "/graphics/med/shared-models/angel-statue/textures/lowpolyangel99_u1_v1_normal.png"
  },
  "/shared-models/bat/textures/Material.001_baseColor.png": {
    "low": "/graphics/low/shared-models/bat/textures/Material.001_baseColor.png",
    "med": "/graphics/med/shared-models/bat/textures/Material.001_baseColor.png"
  },
  "/shared-models/celtic-cross/scene-low.glb": {
    "low": "/graphics/low/shared-models/celtic-cross/scene-low.glb",
    "med": "/graphics/med/shared-models/celtic-cross/scene-low.glb"
  },
  "/shared-models/celtic-cross/textures/tripo_mat_138033c7-ba15-4924-9105-610cbc9ad77b_baseColor.jpeg": {
    "low": "/graphics/low/shared-models/celtic-cross/textures/tripo_mat_138033c7-ba15-4924-9105-610cbc9ad77b_baseColor.jpeg",
    "med": "/graphics/med/shared-models/celtic-cross/textures/tripo_mat_138033c7-ba15-4924-9105-610cbc9ad77b_baseColor.jpeg"
  },
  "/shared-models/cobwebs/textures/cobwebs_baseColor.png": {
    "low": "/graphics/low/shared-models/cobwebs/textures/cobwebs_baseColor.png",
    "med": "/graphics/med/shared-models/cobwebs/textures/cobwebs_baseColor.png"
  },
  "/shared-models/crown/textures/Default.023_baseColor.jpeg": {
    "low": "/graphics/low/shared-models/crown/textures/Default.023_baseColor.jpeg",
    "med": "/graphics/med/shared-models/crown/textures/Default.023_baseColor.jpeg"
  },
  "/shared-models/crown/textures/Default.023_metallicRoughness.png": {
    "low": "/graphics/low/shared-models/crown/textures/Default.023_metallicRoughness.png",
    "med": "/graphics/med/shared-models/crown/textures/Default.023_metallicRoughness.png"
  },
  "/shared-models/crown/textures/Default.023_normal.png": {
    "low": "/graphics/low/shared-models/crown/textures/Default.023_normal.png",
    "med": "/graphics/med/shared-models/crown/textures/Default.023_normal.png"
  },
  "/shared-models/dagger/textures/Material_baseColor.png": {
    "low": "/graphics/low/shared-models/dagger/textures/Material_baseColor.png",
    "med": "/graphics/med/shared-models/dagger/textures/Material_baseColor.png"
  },
  "/shared-models/dagger/textures/Material_metallicRoughness.png": {
    "low": "/graphics/low/shared-models/dagger/textures/Material_metallicRoughness.png",
    "med": "/graphics/med/shared-models/dagger/textures/Material_metallicRoughness.png"
  },
  "/shared-models/dagger/textures/Material_normal.png": {
    "low": "/graphics/low/shared-models/dagger/textures/Material_normal.png",
    "med": "/graphics/med/shared-models/dagger/textures/Material_normal.png"
  },
  "/shared-models/gargoyle-statue/textures/MAT_Statue_Gargoyle5_baseColor.jpeg": {
    "low": "/graphics/low/shared-models/gargoyle-statue/textures/MAT_Statue_Gargoyle5_baseColor.jpeg",
    "med": "/graphics/med/shared-models/gargoyle-statue/textures/MAT_Statue_Gargoyle5_baseColor.jpeg"
  },
  "/shared-models/gargoyle-statue/textures/MAT_Statue_Gargoyle5_normal.png": {
    "low": "/graphics/low/shared-models/gargoyle-statue/textures/MAT_Statue_Gargoyle5_normal.png",
    "med": "/graphics/med/shared-models/gargoyle-statue/textures/MAT_Statue_Gargoyle5_normal.png"
  },
  "/shared-models/gray-wolf/textures/graywoftexture_baseColor.png": {
    "low": "/graphics/low/shared-models/gray-wolf/textures/graywoftexture_baseColor.png",
    "med": "/graphics/med/shared-models/gray-wolf/textures/graywoftexture_baseColor.png"
  },
  "/shared-models/purple-gem/textures/M_Gem_baseColor.png": {
    "low": "/graphics/low/shared-models/purple-gem/textures/M_Gem_baseColor.png",
    "med": "/graphics/med/shared-models/purple-gem/textures/M_Gem_baseColor.png"
  },
  "/shared-models/purple-gem/textures/M_Gem_emissive.jpeg": {
    "low": "/graphics/low/shared-models/purple-gem/textures/M_Gem_emissive.jpeg",
    "med": "/graphics/med/shared-models/purple-gem/textures/M_Gem_emissive.jpeg"
  },
  "/shared-models/purple-gem/textures/M_Gem_metallicRoughness.png": {
    "low": "/graphics/low/shared-models/purple-gem/textures/M_Gem_metallicRoughness.png",
    "med": "/graphics/med/shared-models/purple-gem/textures/M_Gem_metallicRoughness.png"
  },
  "/shared-models/purple-gem/textures/M_Gem_normal.png": {
    "low": "/graphics/low/shared-models/purple-gem/textures/M_Gem_normal.png",
    "med": "/graphics/med/shared-models/purple-gem/textures/M_Gem_normal.png"
  },
  "/shared-models/simple-rock/textures/Material_diffuse.png": {
    "low": "/graphics/low/shared-models/simple-rock/textures/Material_diffuse.png",
    "med": "/graphics/med/shared-models/simple-rock/textures/Material_diffuse.png"
  },
  "/shared-models/simple-rock/textures/Material_normal.png": {
    "low": "/graphics/low/shared-models/simple-rock/textures/Material_normal.png",
    "med": "/graphics/med/shared-models/simple-rock/textures/Material_normal.png"
  },
  "/shared-models/simple-rock/textures/Material_specularGlossiness.png": {
    "low": "/graphics/low/shared-models/simple-rock/textures/Material_specularGlossiness.png",
    "med": "/graphics/med/shared-models/simple-rock/textures/Material_specularGlossiness.png"
  },
  "/shared-models/spider/textures/spider_Mat_baseColor.png": {
    "low": "/graphics/low/shared-models/spider/textures/spider_Mat_baseColor.png",
    "med": "/graphics/med/shared-models/spider/textures/spider_Mat_baseColor.png"
  },
  "/shared-models/sword/textures/wire_135059008_baseColor.jpeg": {
    "low": "/graphics/low/shared-models/sword/textures/wire_135059008_baseColor.jpeg",
    "med": "/graphics/med/shared-models/sword/textures/wire_135059008_baseColor.jpeg"
  },
  "/shared-models/sword/textures/wire_135059008_metallicRoughness.png": {
    "low": "/graphics/low/shared-models/sword/textures/wire_135059008_metallicRoughness.png",
    "med": "/graphics/med/shared-models/sword/textures/wire_135059008_metallicRoughness.png"
  },
  "/shared-models/sword/textures/wire_135059008_normal.jpeg": {
    "low": "/graphics/low/shared-models/sword/textures/wire_135059008_normal.jpeg",
    "med": "/graphics/med/shared-models/sword/textures/wire_135059008_normal.jpeg"
  },
  "/shared-models/wolf/textures/mtl_shiny_lense_eye.002_baseColor.png": {
    "low": "/graphics/low/shared-models/wolf/textures/mtl_shiny_lense_eye.002_baseColor.png",
    "med": "/graphics/med/shared-models/wolf/textures/mtl_shiny_lense_eye.002_baseColor.png"
  },
  "/shared-models/wolf/textures/mtl_wolf_a_body_a.003_baseColor.png": {
    "low": "/graphics/low/shared-models/wolf/textures/mtl_wolf_a_body_a.003_baseColor.png",
    "med": "/graphics/med/shared-models/wolf/textures/mtl_wolf_a_body_a.003_baseColor.png"
  },
  "/shared-models/wolf/textures/mtl_wolf_a_hair_a_body.001_baseColor.png": {
    "low": "/graphics/low/shared-models/wolf/textures/mtl_wolf_a_hair_a_body.001_baseColor.png",
    "med": "/graphics/med/shared-models/wolf/textures/mtl_wolf_a_hair_a_body.001_baseColor.png"
  },
  "/shared-models/wolf/textures/mtl_wolf_a_head_a.003_baseColor.png": {
    "low": "/graphics/low/shared-models/wolf/textures/mtl_wolf_a_head_a.003_baseColor.png",
    "med": "/graphics/med/shared-models/wolf/textures/mtl_wolf_a_head_a.003_baseColor.png"
  },
  "/shared-models/wolf/textures/mtl_wolf_mouth.002_baseColor.png": {
    "low": "/graphics/low/shared-models/wolf/textures/mtl_wolf_mouth.002_baseColor.png",
    "med": "/graphics/med/shared-models/wolf/textures/mtl_wolf_mouth.002_baseColor.png"
  },
  "/shared-textures/adventurer-brown.png": {
    "low": "/graphics/low/shared-textures/adventurer-brown.png",
    "med": "/graphics/med/shared-textures/adventurer-brown.png"
  },
  "/shared-textures/hellhound-fur.png": {
    "low": "/graphics/low/shared-textures/hellhound-fur.png",
    "med": "/graphics/med/shared-textures/hellhound-fur.png"
  },
  "/shared-textures/player-wolf-white-fur.png": {
    "low": "/graphics/low/shared-textures/player-wolf-white-fur.png",
    "med": "/graphics/med/shared-textures/player-wolf-white-fur.png"
  },
  "/textures/door-oak.png": {
    "low": "/graphics/low/textures/door-oak.png",
    "med": "/graphics/med/textures/door-oak.png"
  },
  "/textures/dungeon-floor-stone.png": {
    "low": "/graphics/low/textures/dungeon-floor-stone.png",
    "med": "/graphics/med/textures/dungeon-floor-stone.png"
  },
  "/textures/dungeon-wall-stone.png": {
    "low": "/graphics/low/textures/dungeon-wall-stone.png",
    "med": "/graphics/med/textures/dungeon-wall-stone.png"
  }
};
