import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
const app = new URL('../', import.meta.url);
const output = new URL('public/sprites/', app);
await mkdir(output, { recursive: true });
const bundle = await build({ entryPoints: [new URL('scripts/sprite-baker.ts', app).pathname.replace(/^\/(\w:)/, '$1')], alias: { three: fileURLToPath(new URL('node_modules/three', app)) }, bundle: true, write: false, format: 'iife' });
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-webgl', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
try {
  const page = await browser.newPage();
  await page.route('**/sprite-baker', route => route.fulfill({ contentType: 'text/html', body: '<html><body></body></html>' }));
  await page.goto('http://localhost:3300/sprite-baker');
  await page.addScriptTag({ content: bundle.outputFiles[0].text });
  await page.waitForFunction(() => window.spriteBake || window.spriteError, { timeout: 120000 });
  const error = await page.evaluate(() => window.spriteError); if (error) throw Error(error);
  const sprites = await page.evaluate(() => window.spriteBake);
  const metadata = {};
  for (const [name, { png, ...info }] of Object.entries(sprites)) {
    await writeFile(new URL(`${name}.png`, output), Buffer.from(png.split(',')[1], 'base64'));
    metadata[name] = info;
  }
  await writeFile(new URL('src/client/sprite-metadata.ts', app), '// Generated by npm run build:sprites.\nexport const SPRITE_META = ' + JSON.stringify(metadata, null, 2) + ' as const;\n');
  console.log('Baked ' + Object.keys(metadata).join(', '));
} finally { await browser.close(); }
