import assert from 'node:assert/strict';
import { FloorGrid, castRay } from '../src/client/raycast-world.js';
import { ARENA_X, ARENA_Y, TILE_PX } from '../src/shared/tactics.js';
const grid = new FloorGrid([{ col: -3, row: -2, cols: 8, rows: 6 }]);
const x = ARENA_X + TILE_PX, y = ARENA_Y + TILE_PX;
assert.equal(castRay(grid, x, y, 1, 0).distance, 4 * TILE_PX);
assert.equal(castRay(grid, x, y, -1, 0).distance, 4 * TILE_PX);
assert.equal(castRay(grid, x, y, 0, 1).distance, 3 * TILE_PX);
assert.equal(castRay(grid, x, y, 0, -1).distance, 3 * TILE_PX);
assert.equal(castRay(grid, x, y, 1, .4).distance, 4 * TILE_PX, 'Unnormalized rays retain perpendicular depth');
const gate = { x: x + 20, y, min: y - 10, max: y + 10, vertical: true, material: 1 };
assert.equal(castRay(grid, x, y, 1, 0, [gate]).distance, 20);
assert.equal(castRay(grid, x, y, 1, 0, [gate]).material, 1);
assert.equal(castRay(grid, x, y + 20, 1, 0, [gate]).material, 0, 'No phantom wall outside the gate span');
assert.equal(castRay(grid, x, y, 1, 0, [], 7).distance, 7, 'Camera distance cap');
const joined = new FloorGrid([{ col: 0, row: 0, cols: 5, rows: 5 }, { col: 5, row: 2, cols: 8, rows: 1 }, { col: 13, row: 0, cols: 5, rows: 5 }]);
assert.equal(castRay(joined, ARENA_X + TILE_PX * 2.5, ARENA_Y + TILE_PX * 2.5, 1, 0).distance, TILE_PX * 15.5, 'Corridor seams remain open');
assert.equal(castRay(joined, ARENA_X + TILE_PX * 2.5, ARENA_Y + TILE_PX * 1.5, 1, 0).distance, TILE_PX * 2.5, 'Room wall blocks beside corridor');
console.log('PASS: DDA depths, negative cells, corridor seams, gates, and camera distance.');
import { playerBiteFrame, selectAttackReticle } from '../src/client/attack-presentation.js';
import type { TacticsSnapshot } from '../src/shared/tactics.js';
const biteState = { dead: false, playerEating: false, cooldown: { slot: 0, totalMs: 600, remainingMs: 600 } };
assert.equal(playerBiteFrame(biteState), 0);
biteState.cooldown.remainingMs = 440;
assert.equal(playerBiteFrame(biteState), 4);
biteState.cooldown.remainingMs = 281;
assert.equal(playerBiteFrame(biteState), 7);
biteState.cooldown.remainingMs = 280;
assert.equal(playerBiteFrame(biteState), null, 'Bite ends before the rest of the cooldown');
biteState.cooldown.slot = 1; biteState.cooldown.remainingMs = 600;
assert.equal(playerBiteFrame(biteState), null, 'Ranged cooldown does not bite');
const aim = { player: { x: 0, y: 0 }, playerHeading: { x: 1, y: 0 }, meleeRange: 135, dead: false,
  enemies: [{ id: 'hound', kind: 'hellhound', x: 150, y: 0 }] } as unknown as TacticsSnapshot;
assert.equal(selectAttackReticle(aim, () => true)?.inRange, true, 'Hound allowance matches the former reticle');
assert.equal(selectAttackReticle(aim, () => true)?.aligned, true);
aim.enemies[0]!.x = 250;
assert.equal(selectAttackReticle(aim, () => true)?.inRange, false, 'Aligned but distant is a pale guide');
aim.enemies[0]!.x = 0; aim.enemies[0]!.y = 90;
assert.equal(selectAttackReticle(aim, () => true)?.aligned, false, 'Nearby but sideways is not aligned');
assert.equal(selectAttackReticle(aim, () => false), null, 'Walls hide the reticle');
aim.dead = true;
assert.equal(selectAttackReticle(aim, () => true), null);
console.log('PASS: bite timing, ranged exclusion, reticle range, player-facing alignment, and occlusion.');
import { RaycastRenderer } from '../src/client/raycast-renderer.js';
// Exercise camera input independently of canvas/asset construction.
const camera = Object.create(RaycastRenderer.prototype) as RaycastRenderer;
Reflect.set(camera, 'pitch', 0); camera.yaw = 0;
camera.look(0, .1);
assert(Reflect.get(camera, 'pitch') > 0, 'Mouse up raises the view');
camera.look(0, -.2);
assert(Reflect.get(camera, 'pitch') < 0, 'Mouse down lowers the view');
camera.look(2, 0);
assert(Math.abs(camera.yaw) > Math.PI * 2, 'Horizontal look is not clamped to one revolution');
camera.resetView();
assert.equal(Reflect.get(camera, 'pitch'), 0, 'Reset restores the reference angle');
console.log('PASS: mouse-look pitch in both directions, unrestricted yaw, and view reset.');

import { bloodHits } from '../src/client/blood-effects.js';
const beforeHit = { player: { x: 0, y: 0 }, stats: { health: 100 }, corpses: [],
  enemies: [{ id: 'hound', kind: 'hellhound', x: 50, y: 0, health: 20 }] } as unknown as TacticsSnapshot;
const afterHit = structuredClone(beforeHit);
afterHit.stats.health = 90;
afterHit.enemies[0]!.health = 10;
assert.equal(bloodHits(beforeHit, afterHit).length, 2, 'Simultaneous incoming and outgoing damage both splatter');
assert.equal(bloodHits(afterHit, afterHit).length, 0, 'Repeated snapshots do not replay blood');
const lethalHit = structuredClone(afterHit);
lethalHit.enemies = [];
lethalHit.corpses = [{ ...afterHit.enemies[0]! }];
assert.equal(bloodHits(afterHit, lethalHit).length, 1, 'Lethal removal still spatters');
lethalHit.corpses = [];
assert.equal(bloodHits(afterHit, lethalHit).length, 0, 'Removal without a corpse is not a hit');
const healed = structuredClone(beforeHit);
healed.stats.health = 110;
assert.equal(bloodHits(beforeHit, healed).length, 0, 'Healing does not splatter');
console.log('PASS: damage blood, lethal hits, repeated snapshots, removals, and healing.');
